#!/usr/bin/env bash

# Unofficial Bash Strict Mode (http://redsymbol.net/articles/unofficial-bash-strict-mode/)
set -euo pipefail

printf '%s\n' "Initializing and updating submodules..."

git submodule init && git submodule update --recursive --remote

printf '%s\n' "Linking configuration files/directories for..."

backup_or_remove() {
	if [ -L "$1" ]; then
		rm "$1"
	elif [ -e "$1" ]; then
		if [ -e "$1".old ]; then
			rm -rf "$1".old
		fi
		mv "$1" "$1".old
	fi
}

ensure_dir_exists() {
	if [ ! -d "$1" ]; then
		mkdir -p "$1"
	fi
}

if [ -x "$(command -v aconfmgr)" ]; then
	printf '%s\n' "  aconfmgr..."
	ensure_dir_exists "$HOME"/.config
	backup_or_remove "$HOME"/.config/aconfmgr
	ln -s "$HOME"/dotfiles/aconfmgr "$HOME"/.config/aconfmgr
fi

if [ -x "$(command -v bash)" ]; then
	printf '%s\n' "  bash (and readline)..."
	backup_or_remove "$HOME"/.bashrc
	ln -s "$HOME"/dotfiles/bashrc "$HOME"/.bashrc
	backup_or_remove "$HOME"/.bash_profile
	ln -s "$HOME"/dotfiles/bash_profile "$HOME"/.bash_profile
	backup_or_remove "$HOME"/.inputrc
	ln -s "$HOME"/dotfiles/inputrc "$HOME"/.inputrc
fi

if [ -x "$(command -v dconf)" ]; then
	printf '%s\n' "  dconf (GNOME and GTK)..."
	ensure_dir_exists "$HOME"/.config
	backup_or_remove "$HOME"/.config/autostart
	ln -s "$HOME"/dotfiles/autostart "$HOME"/.config/autostart
	backup_or_remove "$HOME"/.config/dconf
	ln -s "$HOME"/dotfiles/dconf "$HOME"/.config/dconf
	backup_or_remove "$HOME"/.config/gtk-3.0
	ln -s "$HOME"/dotfiles/gtk-3.0 "$HOME"/.config/gtk-3.0
	backup_or_remove "$HOME"/.config/gtk-4.0
	ln -s "$HOME"/dotfiles/gtk-4.0 "$HOME"/.config/gtk-4.0
fi

if [ "nstickney" = "$USER" ] || [ "stickneyn" = "$USER" ]; then
	if [ -x "$(command -v git)" ]; then
		printf '%s\n' "  git..."
		backup_or_remove "$HOME"/.gitconfig
		ln -s "$HOME"/dotfiles/gitconfig "$HOME"/.gitconfig
	fi
fi

if [ -x "$(command -v i3)" ]; then
	printf '%s\n' "  i3wm..."
	backup_or_remove "$HOME"/.i3
	ln -s "$HOME"/dotfiles/i3 "$HOME"/.i3
fi

if [ -x "$(command -v tmux)" ]; then
	printf '%s\n' "  tmux..."
	backup_or_remove "$HOME"/.tmux.conf
	ln -s "$HOME"/dotfiles/tmux.conf "$HOME"/.tmux.conf
fi

if [ -x "$(command -v vim)" ]; then
	printf '%s\n' "  vim..."
	backup_or_remove "$HOME"/.vimrc
	backup_or_remove "$HOME"/.vim
	ln -s "$HOME"/dotfiles/vim "$HOME"/.vim
fi

if [ -x "$(command -v xrdb)" ] && [ -x "$(command -v rofi)" ]; then
	printf '%s\n' "  X.Org (rofi)..."
	backup_or_remove "$HOME"/.Xresources
	ln -s "$HOME"/dotfiles/Xresources "$HOME"/.Xresources
	xrdb "$HOME"/.Xresources
fi
printf '%s\n' "    ...Complete!"

if [ -x "$(command -v sudo)" ]; then
	if [ -x "$(command -v firewall-cmd)" ]; then
		while true; do
			read -r -p "Install firewalld configuration? [y/N]:" -n 1 yn
			echo
			case $yn in
				[Yy]* ) sudo "$HOME"/dotfiles/bin/fw-cmd-init; break;;
				[Nn]* ) break;;
				"" ) break;;
			esac
		done
	fi

	if [ -x "$(command -v iptables)" ]; then
		while true; do
			read -r -p "Install iptables configuration? [y/N]: " -n 1 yn
			echo
			case $yn in
				[Yy]* ) sudo "$HOME"/dotfiles/bin/iptables-init; break;;
				[Nn]* ) break;;
				"" ) break;;
			esac
		done
	fi

	if [ -x "$(command -v nft)" ]; then
		while true; do
			read -r -p "Install nftables configuration? [y/N]: " -n 1 yn
			echo
			case $yn in
				[Yy]* ) sudo "$HOME"/dotfiles/bin/nftables-init; break;;
				[Nn]* ) break;;
				"" ) break;;
			esac
		done
	fi
fi
