" Backup, swap, and undo
set backupdir=$HOME/.cache/vim//  " backup files stored by full file path in /tmp
set directory=$HOME/.cache/vim//  " swap files stored by full file path in /tmp
set undodir=$HOME/.cache/vim//  " undo files stored by full file path in /tmp
set history=1000  " store lots of history
set undofile  " enable persistent undo
set writebackup  " write backups before writing files

" Clipboard (wayland integration using wl-clipboard)
" https://www.reddit.com/r/Fedora/comments/ax9p9t/vim_and_system_clipboard_under_wayland/
xnoremap "+y y:call system("wl-copy", @")<cr>
nnoremap "+p :let @"=substitute(system("wl-paste --no-newline"), '<C-v><C-m>', '', 'g')<cr>p
nnoremap "*p :let @"=substitute(system("wl-paste --no-newline --primary"), '<C-v><C-m>', '', 'g')<cr>p

" Encoding (set to UTF-8 where available)
set encoding=utf-8
scriptencoding utf-8
if v:lang =~? 'utf8$'
	set fileencodings=usc-bom,utf-8
endif

" Git (vim-signify)
let g:signify_realtime = 1              " more aggressive sign updates
let g:signify_cursorhold_normal = 0     " avoid auto-saving buffer
let g:signify_cursorhold_insert = 0     " avoid auto-saving buffer
nmap <Leader>t <Plug>(signify-prev-hunk)
nmap <Leader>g <Plug>(signify-next-hunk)
highlight clear Normal
highlight Normal     cterm=bold
highlight clear SignColumn
highlight SignColumn cterm=bold
highlight clear DiffAdd   
highlight DiffAdd    cterm=bold
highlight clear DiffChange
highlight DiffChange cterm=bold
highlight clear DiffDelete
highlight DiffDelete cterm=bold

" Indentation
if has('autocmd')
	filetype plugin indent on
endif
set autoindent
set shiftwidth=4 softtabstop=4 tabstop=4  " tabs are four characters wide
set cindent cinoptions=(0,u0,U0  " indent with tabs, align with spaces
highlight SpecialKey ctermfg=8|  " indentation guides are dark gray
set list listchars=tab:\│\  " indentation guide (tabs)
let g:indentLine_char_list = ['|', '¦', '┆', '┊']  " indentation guide (spaces)
"" Auto-indent pasted text
nnoremap p p=`]<C-o>
nnoremap P P=`]<C-o>
"" Auto-indent entire file
nnoremap <Leader><tab> <esc>gg=G<C-o><C-o>zz

" Linting (ALE)
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_echo_msg_format = '[%severity%][%linter%]% code:% %s'
nmap <C-k> <Plug>(ale_previous_wrap)
nmap <C-j> <Plug>(ale_next_wrap)

" Mappings
"" Insert a timestamp
nmap <F3> i<C-R>=strftime("%Y-%m-%d %H:%M")<CR><Esc>
imap <F3> <C-R>=strftime("%Y-%m-%d %H:%M")<CR>
"" List highlight groups applied under the cursor
map <F10> :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . 
			\ '> trans<' . synIDattr(synID(line("."),col("."),0),"name") . 
			\ "> lo<"
			\ . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . 
			\ ">"<CR>
"" Open a vertical terminal
nmap ` :vert term<CR>
"" Write the current file
nnoremap <Leader><CR> :write<CR>
"" Write the current file, and quit
nnoremap <Leader>q :wq<CR>
"" Write the current file, using sudo
cnoremap w!! execute 'silent! write !sudo tee % >/dev/null' <bar> edit!

" Mouse
set mouse=a  " use the mouse in all modes

" Navigation
set backspace=indent,eol,start  " backspace wraps lines
if v:version > 703 || v:version == 703 && has('patch541')
  set formatoptions+=j  " Delete comment character when joining commented lines
endif
if !exists('g:loaded_matchit') && findfile('plugin/matchit.vim', &runtimepath) ==# ''
	runtime! macros/matchit.vim  " use % to jump from if to endif
endif
set whichwrap=<,>,[,]  " cursor keys wrap lines

" Scrolling
set scrolloff=4  " start scrolling 4 rows away from top and bottom
set sidescrolloff=4  " start scrolling 4 columns away from edges
set sidescroll=1  " scroll one column at a time sideways

" Search
set hlsearch  " highlight searches; hit escape twice to clear the highlight
if maparg('<Esc><Esc>', 'n') ==# ''
	nnoremap <silent> <Esc><Esc> <Esc>:nohlsearch<Esc>
endif
set incsearch  " search as you type
set smartcase  " ignore case unless a capital is typed

" Spelling
if has('spell')
	set spelllang=en_us
	set spellfile=$HOME/dotfiles/vim/stick.utf-8.add
	set spell
	highlight clear SpellBad
	highlight SpellBad cterm=underline ctermbg=None ctermfg=None
	highlight clear SpellCap
	highlight SpellCap cterm=italic
	highlight clear SpellLocal
	highlight clear SpellRare
endif

" Splits
set diffopt+=vertical  " diff splits vertically by default
set splitbelow  " horizontal splits will place new pane below
set splitright  " vertical splits will place new pane to the right

" Typos
command-bang Q q<bang>
command-bang QW wq<bang>
command-bang Qw wq<bang>
command-bang W w<bang>
command-bang WQ wq<bang>
command-bang Wq wq<bang>

" Visuals
set background=dark  " use dark mode syntax highlighting
set listchars+=trail:-,extends:>,precedes:<,nbsp:+  " 
set showcmd  " show commands as they are typed
set wildmenu  " show completions for menu items
if has('syntax') && !exists('g:syntax_on')
	syntax enable  " apply syntax highlighting
endif
"" Conceal
set conceallevel=2 concealcursor=nc
"" Guides
set colorcolumn=80,90,100,120
highlight clear ColorColumn
highlight ColorColumn ctermbg=8|  " guide columns are dark gray
"" Line Numbers
highlight clear LineNr
highlight LineNr ctermfg=8|  " line numbers should be dark gray
set cursorline  " highlight the current line
highlight clear CursorLine
highlight clear CursorLineNr
highlight CursorLine cterm=None|  " don't highlight the line itself ...
highlight CursorLineNr ctermfg=7|  " but increase brightness on the line number
"" Status and Tab lines (lightline)
set laststatus=2  " always show the status line
set showtabline=2  " always show the tab line
set noshowmode  " showing mode is unnecessary with status line plugin
let g:lightline = {
			\ 'active': {
			\ 'left': [[ 'mode', 'paste' ],
			\ [ 'filename', 'readonly', 'modified' ]],
			\ 'right': [[ 'lineinfo' ],
			\ [ 'percent' ],
			\ [ 'checking', 'warnings', 'errors', 'linter_ok' ]]
			\ },
			\ 'colorscheme' : 'soml',
			\ 'component_expand': {
			\ 'buffers': 'lightline#bufferline#buffers',
			\ 'checking': 'lightline#ale#checking',
			\ 'warnings': 'lightline#ale#warnings',
			\ 'errors': 'lightline#ale#errors',
			\ 'linter_ok': 'lightline#ale#ok'
			\ },
			\ 'component_type': {
			\ 'buffers': 'tabsel',
			\ 'checking': 'left',
			\ 'warnings': 'warning',
			\ 'errors': 'error',
			\ 'linter_ok': 'left'
			\ },
			\ 'tabline' : {
			\ 'left': [ ['buffers'] ],
			\ 'right': [ ['fileformat', 'fileencoding', 'filetype'] ],
			\ }}
let g:lightline#ale#indicator_checking = '...'
let g:lightline#ale#indicator_warnings = '?'
let g:lightline#ale#indicator_errors = '!'
let g:lightline#ale#indicator_ok = ''
"" Wrapping
set linebreak wrap  " wrap lines, but only on whitespace/punctuation
if v:version > 704 || v:version == 704 && has('patch338')
	set breakindent breakindentopt=min:20,shift:2,sbr
endif
