[[block]]
block = "focused_window"
max_width = 100

[[block]]
block = "custom"
interval = 1000
cycle = ["echo  $(hostname -i)", "echo  $(uname -n)", "echo  $(uname -r)", "echo  $(whoami)"]

[[block]]
block = "pacman"

[[block]]
block = "cpu"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
clickable = false

[[block]]
block = "disk_space"
path = "/"
alias = ""

[[block]]
block = "disk_space"
path = "/home/nstickney/SafeDepositBox"
alias = ""

[[block]]
block = "time"
interval = 1
format = "%a %Y.%m.%d %T"

[[block]]
block = "custom"
interval = 1
command = "~/dotfiles/bin/lockleds"
