[[block]]
block = "focused_window"
max_width = 100

[[block]]
block = "custom"
interval = 1000
command = "uname -nr"

[[block]]
block = "custom"
interval = 30
command = "hostname -i"

[[block]]
block = "pacman"

[[block]]
block = "cpu"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
clickable = false

[[block]]
block = "disk_space"
path = "/"
alias = ""

[[block]]
block = "disk_space"
path = "/home"
alias = ""

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
format = "%a %Y.%m.%d %T"

[[block]]
block = "custom"
interval = 1
command = "~/dotfiles/bin/lockleds.sh"
