icons = "awesome"

[theme]
name = "plain"
[theme.overrides]
idle_bg = "#1b1b1b"
idle_fg = "#e2e2e2"
info_bg = "#1b1b1b"
info_fg = "#e2e2e2"
good_bg = "#1b1b1b"
good_fg = "#86b693"
warning_bg = "#1b1b1b"
warning_fg = "#c8a565"
critical_bg = "#1b1b1b"
critical_fg = "#ff7384"
separator = ""
separator_bg = "auto"
separator_fg = "auto"
alternating_tint_bg = "#1b1b1b"
