icons = "awesome"

[theme]
name = "plain"
[theme.overrides]
idle_bg = "#111111"
idle_fg = "#fff8e7"
info_bg = "#111111"
info_fg = "#fff8e7"
good_bg = "#111111"
good_fg = "#fff8e7"
warning_bg = "#cc4400"
warning_fg = "#111111"
critical_bg = "#cc0099"
critical_fg = "#111111"
separator = ""
separator_bg = "auto"
separator_fg = "auto"
alternating_tint_bg = "#111111"
