icons = "awesome"

[theme]
name = "plain"
[theme.overrides]
idle_bg = "#181100"
idle_fg = "#fff8e7"
info_bg = "#181100"
info_fg = "#fff8e7"
good_bg = "#181100"
good_fg = "#fff8e7"
warning_bg = "#cfa117"
warning_fg = "#fff8e7"
critical_bg = "#cf4517"
critical_fg = "#181100"
separator = ""
separator_bg = "auto"
separator_fg = "auto"
alternating_tint_bg = "#181100"
