""" http://marcgg.com/blog/2016/03/01/vimrc-example/
""" https://github.com/skwp/dotfiles/blob/master/vimrc

" The basics
set nocompatible                        " use vim settings instead of vi (must be first)
filetype plugin on                      " filetype based on filenames
filetype indent on                      " indent based on filetype
set autoread                            " automatically reload files changed outside vim
set backspace=indent,eol,start whichwrap+=<,>,[,]   " backspace/cursor keys wrap lines
set colorcolumn=90                      " add a right column for line width
set guifont=Inconsolata\ Medium:12      " font selection
set hidden                              " buffers can exist without being in a window
set history=1000                        " store lots of history
set nocursorline                        " highlight current line number
set number                              " show line numbers
set showmatch                           " highlight matching [{()}]
set showmode                            " show current mode in bottom bar
set showcmd                             " show commands in bottom bar
syntax on                               " use syntax highlighting based on filetype

" Encodings (set to UTF-8 where available)
if v:lang =~ "utf8$" || v:lang =~ "UTF-8$"
   set fileencodings=ucs-bom,utf-8,latin1
endif

" Eyecandy
hi Normal guibg=NONE ctermbg=NONE       " Transparent background
set t_Co=16                             " Use the 16 terminal colors

" Faster
set lazyredraw                          " redraw only as needed
set ttyfast                             " faster redraw

" Folding
set foldmethod=indent                   " fold based on indent
set foldnestmax=3                       " deepest fold is 3 levels
set nofoldenable                        " don't fold by default

" Indentation
nnoremap p p=`]<C-o>                    " auto-indent pasted text
nnoremap P P=`]<C-o>                    " auto-indent pasted text
set autoindent
set expandtab
set nowrap
set shiftwidth=4
set smartindent
set smarttab
set softtabstop=4                       " 4-space tab insertion
set tabstop=4                           " tabs are four characters wide

" Scrolling
set scrolloff=8                         " start scrolling 8 lines away from margins
set sidescrolloff=15
set sidescroll=1

" Searches
set hlsearch                            " highlight searches
set ignorecase                          " ignore case searching
set incsearch                           " search as you type
set smartcase                           " stop ignoring case if a capital is typed

" Swap files (turned off)
set nobackup
set noswapfile
set nowb

" Wildcards
set wildmode=list:longest
set wildmenu                            " ctrl-n and ctrl-p scroll thru matches
set wildignore=*.o,*.obj,*~             " stuff to ignore when tab completing
set wildignore+=*vim/backups*
set wildignore+=*sass-cache*
set wildignore+=*DS_Store*
set wildignore+=vendor/rails/**
set wildignore+=vendor/cache/**
set wildignore+=*.gem
set wildignore+=log/**
set wildignore+=tmp/**
set wildignore+=*.png,*.jpg,*.gif
