#!/bin/sh

#-r asciidoctor-html5s \
/usr/bin/asciidoctor \
	--attribute tabsize=4 \
	--attribute source-highlighter=rouge \
	--attribute rouge-css=style \
	--attribute rouge-style=base16.monokai \
	"$@"
