[colors.bright]
black = "#363636"
red = "#ff7779"
green = "#caa144"
yellow = "#fa8054"
blue = "#67aaff"
magenta = "#df85c0"
cyan = "#52bf93"
white = "#e6e6e6"

[colors.normal]
black = "#0d0d0d"
red = "#ce5055"
green = "#9c7b31"
yellow = "#c2603d"
blue = "#3d81d4"
magenta = "#ac6594"
cyan = "#3c9370"
white = "#c5c5c5"

[colors.primary]
background = "#0d0d0d"
foreground = "#c5c5c5"

[font]
size = 12.0

[font.normal]
family = "Source Code Pro"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[window]
dynamic_padding = true
opacity = 0.93
