[colors.bright]
black = "#444444"
red = "#ffa5a4"
green = "#5bd2a2"
yellow = "#e3b752"
blue = "#90c0ff"
magenta = "#fba0db"
cyan = "#ffa789"
white = "#bbbbbb"

[colors.normal]
black = "#111111"
red = "#fa7779"
green = "#00b681"
yellow = "#c99800"
blue = "#56a2ff"
magenta = "#e77ac3"
cyan = "#f67d52"
white = "#eeeeee"

[colors.primary]
background = "#111111"
foreground = "#eeeeee"

[font]
size = 12.0

[font.normal]
family = "Source Code Pro"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[window]
dynamic_padding = true
opacity = 0.93
