#!/bin/sh

_files=$(git diff --cached --name-only)

# Optimize Images #############################################################

if [ -x "$(command -v gifsicle)" ]; then
	for file in $(printf '%s\n' "$_files" | grep -i ".\.gif\$"); do
		gifsicle --batch --optimize --verbose "$file" 2>&1 |
			sed 's/^/	GIFSICLE: /'
		git add "$file"
	done
fi

if [ -x "$(command -v jpegoptim)" ]; then
	for file in $(printf '%s\n' "$_files" | grep -i -e ".\.jpg\$" -e ".\.jpeg\$"); do
		printf '** Processing: %s\n' "$file"
		jpegoptim "$file" 2>&1 | sed 's/^/	JPEGOPTIM: /'
		git add "$file"
	done
fi

if [ -x "$(command -v optipng)" ]; then
	for file in $(printf '%s\n' "$_files" | grep -i ".\.png\$"); do
		optipng "$file" 2>&1 |
			sed '/^$/d' | sed -e 1b -e '$!d' | sed 's/^/	OPTIPNG: /'
		git add "$file"
	done
fi
